jqCronDefaultSettings.texts.sr = {
	empty: '-svi-',
	empty_minutes: 'minuta',
	empty_time_hours: 'svakog sata',
	empty_time_minutes: 'svakog minuta',
	empty_day_of_week: 'svakog dana u sedmici',
	empty_day_of_month: 'svakog dana u mesecu',
	empty_month: 'svakog meseca',
	name_none: 'prazno',
	name_minute: 'svakog',
	name_hour: 'svakog sata',
	name_day: 'svakog dana',
	name_week: 'sedmično',
	name_month: 'mesečno',
	name_year: 'godišnje',
	text_period: '<b />',
	text_mins: ' u <b /> minuta posle punog sata',
	text_time: ' u <b />:<b />',
	text_dow: ' <b />',
	text_month: ' <b />',
	text_dom: ' <b />',
	error1: 'Tag %s nije podržan!',
	error2: 'Netačan broj elemenata',
	error3: 'jquery_element treba biti deo jqCron settings objekta',
	error4: 'Iskaz nije prepoznat',
	weekdays: ['ponedeljak', 'utorak', 'sreda', 'četvrtak', 'petak', 'subota', 'nedelja'],
	months: ['januar', 'februar', 'mart',  'april', 'maj', 'jun', 'jul', 'avgust', 'septembar', 'octobar', 'novembar', 'decembar']
};
