jqCronDefaultSettings.texts.de = {
	empty: '-all-',
	empty_minutes: 'every',
	empty_time_hours: 'every hour',
	empty_time_minutes: 'every minute',
	empty_day_of_week: 'every day of the week',
	empty_day_of_month: 'every day of the month',
	empty_month: 'every month',
	name_none: 'none',
	name_minute: 'every',
	name_hour: 'hourly',
	name_day: 'daily',
	name_week: 'weekly',
	name_month: 'monthly',
	name_year: 'yearly',
	text_period: '<b />',
	text_mins: ' at <b /> minute(s) past the hour',
	text_time: ' at <b />:<b />',
	text_dow: ' on <b />',
	text_month: ' of <b />',
	text_dom: ' on <b />',
	error1: 'The tag %s is not supported !',
	error2: 'Bad number of elements',
	error3: 'The jquery_element should be set into jqCron settings',
	error4: 'Unrecognized expression',
	weekdays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
	months: ['january', 'february', 'march',  'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']
};
